# Site
name: "MaakBib"
title: "MaakBib"
description: "De MaakBib website, wat ga jij maken?"
logo: 'assets/images/logo.png'
logoheader: 'assets/images/logoMaakbibHeader.png'
favicon: 'assets/images/favicon.ico'
baseurl: 
google_analytics: ''
#disqus: 'demowebsite'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  cri:
    name: Cristina
    display_name: Cristina
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: cristina@decreatievestem.be
    web: https://decreatievestem.be
    twitter: https://twitter.com/
    description: "Oprichter van De Creatieve STEM. Workshops begeleiden, workshops maken, opleiden, inspireren, ze doet het allemaal."
  ben:
    name: Benny
    display_name: Benny    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: benny.malengier@decreatievestem.be
    web: https://decreatievestem.be
    twitter: https://twitter.com/
    description: "Benny verzorgt de IT, en is onderzoeker bij de UGent. Hij ontwikkeld workshops rond IoT, Arduino en meer. Hij is ook de auteur van blokkencode.ingegno.be"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
